# Generated by Django 4.2.4 on 2023-08-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Is pleasant')),
                ('frequency', models.IntegerField(default=1, verbose_name='Frequency')),
                ('reward', models.CharField(max_length=255, verbose_name='Reward')),
                ('execution_time', models.IntegerField(blank=True, null=True, verbose_name='Execution time')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Related habit')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
    ]
