# Generated by Django 4.2.5 on 2023-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='eta',
            field=models.PositiveIntegerField(help_text='не больше 120 секунд', verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(default=1, help_text='не больше 7', verbose_name='периодичность'),
        ),
    ]