# Generated by Django 4.2.4 on 2023-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reward'),
        ),
    ]
