# Generated by Django 4.2.4 on 2023-08-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Chat ID'),
        ),
    ]
